name: nostr
description: A library for nostr protocol implemented in dart for flutter
version: 1.3.1
homepage: https://github.com/ethicnology/dart-nostr

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0
  json_serializable: ^6.1.3
dependencies:
  bip340: ^0.0.4
  convert: ^3.1.1
  crypto: ^3.0.2
  json_annotation: ^4.8.0
